import Head from "next/head";
import styles from "../styles/Home.module.css";
import { getEntriesData } from "../data/entries/entries";
import EntryList from "../components/EntryList";

export async function getStaticProps() {
  const entries = await getEntriesData();
  return {
    props: {
      entries,
    },
  };
}

export default function Home({ entries }) {
  return (
    <div className="container mx-auto px-4">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <EntryList entries={entries} />
      </main>
    </div>
  );
}
